[metadata]
name = pyrisma
version = 0.0.1
author = Marley
author_email = marleysbenicio@gmail.com
description = Biblioteca Python para exibir mensagens coloridas e com ícones no terminal.
long_description = file: README.md
long_description_content_type = text/markdown

license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Topic :: Software Development :: Libraries

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
include_package_data = True

[options.packages.find]
where = src
